const assert = require('node:assert/strict');
const { buildSync } = require('esbuild');
const { mkdtempSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
(async () => {
  const dir = mkdtempSync(join(tmpdir(), 'zepp-ui-state-'));
  try {
    const outfile = join(dir, 'utils.mjs');
    buildSync({entryPoints:['zepp_report/static/frontend-utils.js'],bundle:true,format:'esm',platform:'node',outfile});
    const {shiftRange,clampDay,createDayCache} = await import(outfile);
    assert.deepEqual(shiftRange('2024-03-01','2024-03-31',-1), ['2024-02-01','2024-02-29']);
    assert.deepEqual(shiftRange('2024-02-01','2024-02-29',1), ['2024-03-01','2024-03-31']);
    assert.deepEqual(shiftRange('2024-01-01','2024-12-31',-1), ['2023-01-01','2023-12-31']);
    assert.deepEqual(shiftRange('2026-09-03','2026-09-09',-1), ['2026-08-27','2026-09-02']);
    assert.equal(clampDay('2026-08-31','2026-09-01','2026-09-28'),'2026-09-01');
    let resolvers=[],calls=0;
    const cache=createDayCache(()=>{calls++;return new Promise(resolve=>resolvers.push(resolve))});
    const old=cache.get('day');
    assert.equal(cache.get('day'),old,'in-flight requests are shared');
    cache.clear();
    const fresh=cache.get('day');
    assert.equal(calls,2,'invalidation must not reuse old request');
    resolvers[1]({revision:'new'});await fresh;
    resolvers[0]({revision:'old'});await old;
    assert.deepEqual(await cache.get('day'),{revision:'new'},'late response cannot overwrite new cache');
    const samplingFile=join(dir,'sampling.mjs');
    buildSync({entryPoints:['zepp_report/static/display-sampling.js'],bundle:true,format:'esm',platform:'node',outfile:samplingFile});
    const {displaySamples,pixelBudget}=await import(samplingFile);
    const start=1700000000123;
    const steps=Array.from({length:1440},(_,i)=>({time:start+i*60000,value:i===20?null:i===30?255:i%13}));
    const sampled=displaySamples(steps,'steps',{budget:600});
    assert.equal(sampled.method,'sum');
    assert.ok(sampled.points.length<=600);
    assert.equal(sampled.points.reduce((sum,p)=>sum+(p.value??0),0),steps.reduce((sum,p)=>sum+(p.value??0),0),'step interval sums conserve all recorded steps');
    assert.ok(sampled.points.some(p=>p.missing>0&&p.partial),'null minute creates partial bucket');
    const hole=steps.filter((_,i)=>i<100||i>=120);
    const gapped=displaySamples(hole,'steps',{budget:600});
    assert.ok(gapped.points.some(p=>p.value===null&&p.missing===p.expected),'entire missing interval stays null, never0');
    const zero=displaySamples(Array.from({length:20},(_,i)=>({time:start+i*60000,value:0})),'steps',{budget:8});
    assert.ok(zero.points.every(p=>p.value===0),'recorded zeros remain real zeros');
    const vital=steps.map((p,i)=>({...p,value:i===501?190:i===700?35:65}));
    const envelope=displaySamples(vital,'heart_rate',{budget:100});
    assert.equal(envelope.method,'envelope');assert.ok(envelope.points.length<=100);
    assert.ok(envelope.points.some(p=>p.time===vital[501].time&&p.value===190));
    assert.ok(envelope.points.some(p=>p.time===vital[700].time&&p.value===35));
    assert.deepEqual(envelope.points[0],vital[0]);assert.deepEqual(envelope.points.at(-1),vital.at(-1));
    assert.ok(envelope.points.every(p=>vital.some(source=>source.time===p.time&&source.value===p.value)),'envelope timestamps and values must come from actual samples');
    const zoom=displaySamples(vital,'heart_rate',{from:vital[500].time,to:vital[509].time,budget:100});
    assert.equal(zoom.method,'raw');assert.deepEqual(zoom.points,vital.slice(500,510),'zoom recomputes exact originals, not coarse samples');
    assert.ok(zoom.points.every(p=>p.time>=vital[500].time&&p.time<=vital[509].time));
    assert.equal(displaySamples([{time:start,value:null}],'spo2',{budget:8}).points.length,0);
    assert.equal(pixelBudget(300),600);assert.equal(pixelBudget(2000),1200);
    console.log('UI state: periods, cache races, sampling totals/extremes/gaps/zoom passed');
  } finally {rmSync(dir,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exit(1)});
