apiVersion: 1
datasources:
  - name: Zepp VictoriaMetrics
    uid: zepp-victoriametrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: ${VM_QUERY_URL}
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 1m
